#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

void literallyunbeatable();
int guessmeharder(int);

int main() {
	char howtheydoin[128];
	int hash;

	setbuf(stdout, NULL);
	setbuf(stdin, NULL);
	setbuf(stderr, NULL);

	printf("Welcome to BCA's COVID-19 support services.\n");
	printf("For information about the Haphazardly Elucidative Pseudorandom Artifact filters, enter '1'.\n");
	printf("If you want to know BCA is dealing with COVID-19, enter '2'.\n");
	printf("If you're under a lot of pressure, and you want to tell us how you're doing, enter anything else.\n");
	

	fgets(howtheydoin, 120, stdin);
	if (strstr(howtheydoin, "1")) { // Checks if '1' is contained in the input
		printf("Our top-of-the-line filters mean any random number is guaranteed to be seeded through quantum fluctuations in the very fabric of space.\n");
		printf("We would never do something as insecure as seeding random number generation with user input. That would cause contamination.\n");
		printf("We suggest staying 6ft away from any application that seeds random number generation with user input.\n");
	} else if (strstr(howtheydoin, "2")) // Checks if '2' is contained in the input
		printf("I was going to say something cynical here, but I might get fired, so I probably shouldn't...\nIt's going...\nGreat!\n");
	else if (strstr(howtheydoin, "flag")) { // Checks if 'flag' is contained in the input
		printf("I get it, I get it, you want the flag. All you mischievous prefrosh want to do is use the flag to unlock the filter.\n");
		printf("Unluckily for you, the code to unlock the filter hidden behind these impossible-to-guess random numbers.");
		hash = howtheydoin[0] + 3 * howtheydoin[1] + 7 * howtheydoin[2]; // Probably safe
		srand(hash); // `hash` is guaranteed to be generated by quantum fluctuations in the very fabric of space.
		literallyunbeatable();
	} else 
		printf("I don't get paid enough to be your counselor and listen to your problems. Talk to a therapist or something.\n");
	return 0;
}

void literallyunbeatable() {
	int i = 1;
	printf("You'll never guess these impossible numbers!\n");
	if (!guessmeharder(i++))
		printf("See? I told you, literally impossible.\n");
	else if (!guessmeharder(i++))
		printf("What, did you get the first one on a fluke?\n");
	else if (!guessmeharder(i++))
		printf("This is getting weird...\n");
	else if (!guessmeharder(i++))
		printf("Oh thank god you failed I was so scared\n");
	else if (!guessmeharder(i++))
		printf("Wow you failed on the last one, what a loser\n");
	else {
		printf("NANI!?!? That's.........IMPOSSIBLE!!1!1!!!!1!\n");
		printf("Well, I have no choice but to give you this flag. It's policy, and everybody knows BCA ***NEVER*** relaxes policy.\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("Except for sometimes, but you get it.\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("There, I found it. Enjoy:\n");
		system("cat flag.txt");
	}
}

int guessmeharder(int i) {
	int r = rand();
	int g;
	printf("Enter guess %d here:", i);
	scanf("%d", &g);
	return r == g;
}