version: "2.0"
services:
  web:
    build: .
    ports:
      - 1337
    environment:
      LOGIN1_FLAG: "camp{client_side_is_a_terrible_idea_Fw9dgptH}"
      LOGIN1_PASSWORD: thisisaverysecurepasswordhahaaaaaa