version: "2.0"
services:
  web:
    build: .
    environment:
      LOGIN2_FLAG: "camp{sql_1nj3ct10n_1s_quite_nice_txWks8wC}"
      LOGIN2_PASSWORD: uqhreo8quyr9uqwyeroiusaydfouahsdouqwyoruyqn239487214riuyhsandoifuhqoidruhyasdlifuhaskdjfb
  proxy:
    image: nginx
    ports:
      - 20005:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /ssl:/etc/ssl
    depends_on:
      - web
