#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>

#define EEEE NULL
#define eeEE system("cat E");

void EEEEEEEEE();
int EEEEEEEEEEE();

int main() {
	char e[128];

	setbuf(stdout, NULL);
	setbuf(stdin, NULL);
	setbuf(stderr, NULL);

	printf("EEEEEEEEEEEEEEEEEEEEEit's at the beginnings of ends\n");
	
	fgets(e, 120, stdin);
	if (strstr(e, "Ee")) // Checks if Ee
		printf("EEEEEEEEEEEEEEEEEEEEEEEand the end of the middle.\n");
	else if (strstr(e, "EEe")) // Checks if EEe
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEthe end of time and space\n");
	else if (strstr(e, "EEEEEEEEEEEEEE")) { // Checks if EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEbut the beginning of everything");
		srand(time(EEEE)); // `hash` is guaranteed to be generated by quantum fluctuations in the very fabric of timeeeeEEEEEEEE.
		EEEEEEEEE();
	} else 
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEit's at the end of nowhere and the beginning of everywhere\n");
	return 0;
}

void EEEEEEEEE() {
	printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEwhat a loser\n");
	else {
		printf("NANIEEEEEEEEEEEEEEEEEEEEEEEEE\n");
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("E\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("EEEEEEEEEEEjoy\n");
		eeEE
	}
}

int EEEEEEEEEEE() {
	int e = rand();
	int ee;
	printf("E:");
	scanf("%d", &ee);
	return e == ee;
}