#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define EEEE NULL
#define eeEE "cat E"

void EEEEEEEEEEE();
int EEEEEEEEEEE(int);

int main() {
	char e[128];
    printf("EEEEEEEEEEEEEEEEEEEEEit's at the beginning of ends\n");
	
    fgets(e, 120, stdin);
	if (strstr(e, "1")) { // Checks if E
		printf("EEEEEEEEEEEEEEEEEEEEEEEand the end of the middle.\n");
	} else if (strstr(e, "2")) // Checks if EE
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEthe end of time and space\n");
	else if (strstr(e, "EEEEEEEEEEEEEE")) { // Checks if EEEEEEEEEEEEEEEEEEEEEEEEEEEEE
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEbut the beginning of everything");
		srand(time(EEEE)); // `hash` is guaranteed to be generated by quantum fluctuations in the very fabric of EEEEEEEEEEEE.
		EEEEEEEEEEE();
	} else 
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEit's at the end of nowhere and the beginning of everywhere\n");
	return 0;
}

void EEEEEEEEEEE() {
	printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEEEEE\n");
	else if (!EEEEEEEEEEE())
		printf("EEEEEEEEEEEEEEEEEEEEwhat a loser\n");
	else {
		printf("NANIEEEEEEEEEEEEEEEEEEEEEEEEE\n");
		printf("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("E\n");
		sleep(1);
		printf("\n");
		sleep(1);
		printf("EEEEEEEEEEEjoy\n");
		system(eeEE);
	}
}

int EEEEEEEEEEE() {
	int e = rand();
	int ee;
	printf("E:");
	scanf("%d", &ee);
	return e == ee;
}