FROM nginx:latest
COPY html/index.html /var/www/html/index.html
COPY html/flag-obfuscated.js /var/www/html/flag-obfuscated.js
COPY html/prism.css /var/www/html/prism.css
COPY html/prism.js /var/www/html/prism.js