version: "2.0"
services:
  web:
    build: .
    environment:
      APH2_FLAG: "camp{1ntr0sp3c10n_yXLw7nXa2zNvX5Nd}"
  proxy:
    image: nginx
    ports:
      - 20004:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /ssl:/etc/ssl
    depends_on:
      - web
